name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "tournament-server/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
    - name: Install SSH private key
      run: |
        echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST}} 'echo Hello World'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
